apiVersion : apps/v1
kind: Deployment
metadata:
  name: "troubleshooting-app"
  namespace: troubleshooting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "troubleshooting-app"
  template:
    metadata:
      labels:
        app: "troubleshooting-app"
    spec:
      containers:
        - name: "troubleshooting-app"
          image: cepgbaseacr.azurecr.io/troubleshooting:latest
          resources:
            limits:
              memory: 64Mi
              cpu: 50m
            requests:
              memory: 32Mi
              cpu: 25m
